import { AxiosResponse } from 'axios';
import type { NextPage, GetServerSideProps } from 'next';
import Head from 'next/head'
import ArticleList from '../components/ArticleList';
import Tabs from '../components/Tabs';
import { fetchArticles, fetchCategories } from '../http';
import { IArticle, IPagination, ICategory, ICollectionResponse, IQueryOptions } from '../types';
import qs from 'qs';
import Pagination from '../components/Pagination';
import { useRouter } from 'next/router';
import { debounce } from '../utils';


interface IPropTypes {
  categories: {
    items: ICategory[];
  };
  articles: {
    items: IArticle[];
    pagination: IPagination;
  }
}

const Home: NextPage<IPropTypes> = ({ categories, articles }) => {

  const router = useRouter();

  const { page, pageCount } = articles.pagination;

  const handleSearch = (query: string) => {
    router.push(`/?search=${query}`);
};

  return (
    <>
      <Head>
        <title>Next app</title>
        <meta name="description" content="generated by create next app" />
      </Head>
      <Tabs categories={categories.items} handleOnSearch={debounce(handleSearch, 500)} />
      <ArticleList articles={articles.items} />
      <Pagination page={page} pageCount={pageCount} />
    </>
  )
};

export const getServerSideProps: GetServerSideProps = async ({query}) => {

  const options: Partial<IQueryOptions> = {
    populate: ['author.avatar'],
    pagination: {
      page: query.page ? +query.page : 1,
      pageSize: 3,
    }
  };

  if (query.search) {
    options.filters = {
        Title: {
            $containsi: query.search,
        },
    };
}

  const queryString = qs.stringify(options);

  // categories
  const { data: categories }: AxiosResponse<ICollectionResponse<ICategory[]>> = await fetchCategories();
  const { data: articles }: AxiosResponse<ICollectionResponse<IArticle[]>> = await fetchArticles(queryString);

  console.log(JSON.stringify(queryString))

  return {
    props: {
      categories: {
        items: categories.data
      },
      articles: {
        items: articles.data,
        pagination: articles.meta.pagination,
      }
    }
  }
}

export default Home;
